### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by netmebtc** [iridiumdev/iridium#27]
When I compile the latest version, there is a error:

In file included from /root/ird/iridium/src/NodeRpcProxy/NodeRpcProxy.cpp:6:0:
/root/ird/iridium/src/NodeRpcProxy/NodeRpcProxy.h:141:31: error: array must be initialized with a brace-enclosed initializer
   Crypto::Hash m_lastHash = {0};
                               ^
/root/ird/iridium/src/NodeRpcProxy/NodeRpcProxy.h:142:29: error: array must be initialized with a brace-enclosed initializer
   Crypto::Hash nullHash = {0};

==================
OS: ubuntu 16.04
g++ version: 5.4.0

op step:
$ git clone -b master https://github.com/iridiumdev/iridium.git
$ cd iridium
$ mkdir build
$ cd build
$ cmake -D STATIC=ON -D CMAKE_BUILD_TYPE=RELEASE ..
$ PORTABLE=1 make

**Comment by steevebrush** [comment]
gcc 5.4 does not accept a = {} initialization for array.
